Update build system for Linux, macOS, overhaul GitHub Actions, remove serial driver
REVrobotics/CANBridge pull request #37
Opened 2024-09-23 20:12 UTC by garrettsummerfi3ld

This PR introduces a number of changes to the build system and GitHub Actions workflows, as well as removing the unused serial driver.

* Overhauled GitHub Actions workflows to include Linux, macOS platforms, alongside concurrency for builds and split larger steps into smaller steps for legibility and debugging of failing actions.
  * New runners include X86, ARM32, and ARM64 Linux runners, macOS runners compiling universal binaries alongside the existing Windows runner. ARM runners are using a WPI provided Docker container to build against.
  * Added special rulesets for workflow concurrency for jobs running in sync and queueing builds for branches.
  * Added special rulesets for allowing all branches to run actions instead of only `main` and PRs to `main` for testing builds on multiple platforms before a PR.
  * Split apart larger tasks into smaller tasks for better verbosity during workflow runs.
  * Updated action dependencies to latest as [older actions are deprecated due to old Node.js runtimes](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/).
  * Restructure how artifacts are created, where instead of a single large artifact including CANBridge binaries and WPILib headers, it is now separated into its own artifact as the headers are universal across all platforms.
  * Cleaned up release workflow for pushing tags to create a draft release where instead of using the GitHub CLI, a [dedicated action](https://github.com/softprops/action-gh-release) is used instead for simplicity.
* Updated GoogleTest to fix an issue with macOS utilizing incorrect platform from the WPILib Artifactory. This would fail macOS builds completely.
* ~~Added IOKit linker args for macOS builds to use with the serial driver.~~
* ~~Removed Windows-only preprocessor macros on the serial driver for all platforms.~~
* Removed serial driver completely. This driver was not used, nor supported or maintained.
* Add GitHub Dependabot to automate updating GitHub Actions.

~~There are some changes made in this PR that breaks builds for node-can-bridge, plans to update build and CI for node-can-bridge are underway to incorporate Linux and macOS builds for future releases.~~

PR that addresses these concerns is created at https://github.com/REVrobotics/node-can-bridge/pull/30 for discussion and review.

2024-09-23 21:24 UTC, qwertychouskie commented on build.gradle
> +          linker.args '-framework', 'IOKit'
Is this necessary with the removal of the serial driver?

2024-09-23 21:30 UTC, garrettsummerfi3ld commented on build.gradle
> +          linker.args '-framework', 'IOKit'
This is not necessary as the serial driver is removed. However, building back with SocketCAN or some other framework with CAN would be beneficial to leave in. There is no hurting with keeping it here.

2024-09-23 23:01 UTC, NoahAndrews commented
Thanks for making this (at first glance) so much easier to review! Going to try to get to this this week.

2024-09-28 01:28 UTC, garrettsummerfi3ld commented
This PR had downstream issues with building node-can-bridge, the PR that addresses this concern has been created here: https://github.com/REVrobotics/node-can-bridge/pull/30

2024-11-12 05:09 UTC, NoahAndrews requested changes, later dismissed
Finally got started looking at this in depth! So far, I've got a request to reduce code duplication, and a PR that will add static WPILib dependencies to the artifacts instead of just dynamic ones (https://github.com/unofficial-rev-port/CANBridge/pull/8). I'd strongly recommend reviewing and merging that PR before creating `assemblePlatformSpecificArtifacts.sh`.

2024-11-12 05:16 UTC, NoahAndrews commented on build.gradle
> +          linker.args '-framework', 'IOKit'
I don't think that's true if we end up using DriverKit instead of IOKit. According to this page, DriverKit is an IOKit replacement: https://developer.apple.com/system-extensions/

> DriverKit provides a fully modernized replacement for IOKit to create device drivers.

2024-11-12 05:22 UTC, NoahAndrews commented on build.gradle
> +          linker.args '-framework', 'IOKit'
`USBDriverKit` certainly sounds like what we want: https://developer.apple.com/documentation/usbdriverkit

2024-11-12 05:44 UTC, NoahAndrews commented on build.gradle
> +          linker.args '-framework', 'IOKit'
Looking at the transcript of the video in that first link, there's a lot of emphasis on DriverKit being better than kernel extensions, which I'd think never would have been necessary in the first place for what we're doing.

It seems like DriverKit would require a separate System Extension that would handle all direct communication with the USB device, and then CANBridge would communicate with our DriverKit driver. That would be fine, but I think we'd have to design a whole API between our driver and CANBridge, which does sound like more work.

IOKit (and specifically `IOUSBLib.h`) on the other hand looks like a model more similar to what we're doing on Windows. The "Important" box on [this page ](https://developer.apple.com/documentation/iokit) makes me a bit nervous, but it's really not clear what it's trying to say.

> Devices supported on macOS 11 and later require [DriverKit](https://developer.apple.com/documentation/driverkit). Use IOKit in your apps and services to discover and use devices.

2024-11-12 05:52 UTC, NoahAndrews commented on build.gradle
> +          linker.args '-framework', 'IOKit'
Just noticed this in the DriverKit presentation transcript:

>The DriverKit APIs are an extension of the IOKit APIs to userspace. And we have collected them into a new DriverKit SDK that is separate to the macOS SDK. This SDK has a limited API surface for reliability and security and there is no direct access to the file system, networking, or mock messaging. This allows Apple to tailor the userspace process to running drivers and can give it elevated priority and increased capabilities. So, let's talk about some of the classes in the DriverKit SDK. First, the IOService class exists in DriverKit and is very similar to the IOKit class. There also IOMemoryDescriptor and IOBufferMemoryDescriptor classes available that are, again, very similar to IOKit. We also have replacements for the IOWorkLoop and EventSource classes in IOKit. And finally, there's a new class called OSAction that is required to represent a C Function Pointer.

So yeah, I think IOKit is probably the way to go if we don't need any kind of extra OS-level permissions like a kext would have.

2024-11-18 03:44 UTC, garrettsummerfi3ld commented on build.gradle
> +          linker.args '-framework', 'IOKit'
So from reading about macOS drivers as a whole when I made the PR, its a mess at the moment on which framework to use.

IOKit is only available on macOS but is being given the "deprecated but not deprecated" treatment. Those drivers run as kernel extensions and because in the name of security and stability those are getting moved over to DriverKit which solves the security and stability issues. Lots of documentation for how to do things since its been around for so much longer, but Apple has other ideas on what to do.

If we want maintained support for the future, IOKit will be discouraged from developing for in favor of using DriverKit.

Could be totally misinterpreting this as there was a whole macOS update that happened that added more things to DriverKit that I haven't dived into the docs for but the writing on the wall looks to be there.

2024-11-24 06:10 UTC, qwertychouskie commented on .github/workflows/build.yml
> +      - name: Build
This should be resolved with https://github.com/REVrobotics/CANBridge/pull/37/commits/8265f5225b56f149eb5dc971abe8238cecd1f14e as the workflows are no longer duplicated between the container and non-container versions.  Let me know if this works for you or if you still want the bash code to also be split out into a separate file.

2024-11-24 06:24 UTC, qwertychouskie commented
In addition to fixing the code duplication issue, I also just rebased the PR.  Unless any new issues are found, this should be ready to merge.

2025-05-27 22:28 UTC, LandryNorris commented on .github/dependabot.yml
> +      interval: "weekly"
I only suggest this because it's very easy to change, but can you add a new line to the end of the file? It makes diffs easier as we add lines, and gets rid of GitHub's red icon.

2025-05-27 22:30 UTC, LandryNorris approved these changes
Some comments added, but I'm ok with this as-is also.

2025-05-28 03:52 UTC, qwertychouskie commented
Sorry for the commit noise, the commit list should be clean now.  I squashed the newline addition into the commit that added that file, and dropped the commit that made a trivial change to the serial driver that gets completely removed a couple commits later anyways.

2025-05-28 04:52 UTC, qwertychouskie commented on config.gradle
> -nativeUtils.wpi.addWarningsAsErrors()
Resolved, I dropped the commit that changed this.  It appears build still work as expected.  I suspect this was needed when we were trying to build the old serial driver on other platforms, but since that driver is removed, it does not appear to be necessary.  CI passed: https://github.com/unofficial-rev-port/CANBridge/actions/runs/15291749716/job/43012364789

2025-05-28 04:53 UTC, qwertychouskie commented on build.gradle
> +          linker.args '-framework', 'IOKit'
Dropped for now.  We can re-add this if/when we actually have a macOS CAN driver.

2025-05-28 15:44 UTC, slyboots commented
YOOOOOOOOO! 🚢 🇮🇹

2025-05-28 15:44 UTC, slyboots approved these changes

2025-06-18 15:03 UTC, LandryNorris commented
I can merge it. Is it good on your side?

2025-06-18 15:14 UTC, merged

2025-06-18 20:08 UTC, qwertychouskie commented
@LandryNorris Thanks for getting this merged!  Can you tag a new release of CANBridge so https://github.com/REVrobotics/node-can-bridge/pull/30 can be tested/finalized/merged?

2025-06-26 20:00 UTC, slyboots commented
@qwertychouskie just now noticing this. Did we ever get this done for you?